# ====================================================
# CHAT APPLICATION CONFIGURATION FILE
# This file is installed at: /etc/chat.conf
# ====================================================

# Tên phân vùng Bộ nhớ chia sẻ (POSIX Shared Memory)
SHM_NAME=/shm_chat_pkg_6_5

# Đường dẫn tệp tin nhật ký ghi chép cuộc hội thoại (Log file)
# Tiến trình cần có quyền ghi vào thư mục này
LOG_PATH=/var/log/chat_app.log
